name: debugger-action
on: workflow_dispatch
jobs: 
  debugger-action-job:
    runs-on: ubuntu-latest
    steps:
      - run: touch /tmp/keepalive
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
